### ISSUE TITLE
Suggestions for improvment

### ISSUE THREAD

**Issue by ghost** [pathj/pathj#45]
Dear Marcello,
Thank you for the effort you put into developing modules for Jamovi. This is really appreciated.

Thank you for bringing this package to Jamovi. May I suggest two improvements for this package?
1. (important) In addition to the fit indices provided by the package, there are two or more very common measures missing here. Among these, TLI, CFI, and NFI. These are provided by 'lavaan' but not sure why they are missing here (see for example the CFA package). Can you please add them?
2. I understand that this is a 'path analysis' but I think there is a space to allow for 'latent variable' to be estimated (similar to lavaan). You know, we rely on observed variables to represent the latent one. But in the package, we can only use one variable for each construct. 

Thank you again for your effort and contribution to the field,
Abdullah

**Comment by mcfanda** [comment]
Hi, thanks for the feedback.
1. Very  true, in the next version we include the three missing indices
2. Pathj will remain for observed variables only, but in a few days a new module will come out for latent variables analysis. It consists of two submodules, one being a point-and-click interface to estimate models with latent variables, one that allows writing lavaan syntax. With the second one, one can estimate any model that lavaan does.

**Comment by ghost** [comment]
Good to hear that 👍
